
=head1 NAME

libre-dt-lab-cmstest - test if the color management subsystem of your computer is correctly configured

=head1 SYNOPSIS

    libre-dt-lab-cmstest

=head1 DESCRIPTION

B<libre-dt-lab> is a digital photography workflow application for B<Linux>, B<Mac OS X> and several other B<Unices>.
It's described further in L<libre-dt-lab(1)|libre-dt-lab(1)>.

B<libre-dt-lab-cmstest> investigates if the color management subsystem of your computer is correctly configured and it displays some useful information about the installed monitor profile(s).

=head1 SEE ALSO

L<libre-dt-lab(1)|libre-dt-lab(1)>

=head1 AUTHORS

The principal developer of darktable is Johannes Hanika.
Libre DT-Lab is an experimental fork of darktable.
The (hopefully) complete list of contributors to the project is:

DREGGNAUTHORS -- don't translate this line!

This man page was written by Ulrich Pegelow E<lt>ulrich.pegelow@tongareva.deE<gt> as part of the usermanual.
It was turned into a man page by Tobias Ellinghaus E<lt>me@houz.orgE<gt>.

=head1 COPYRIGHT AND LICENSE

B<Copyright (C)> 2009-2017 by Authors.

B<libre-dt-lab> is free software; you can redistribute it and/or modify it
under the terms of the GPL v3 or (at your option) any later version.

